# Generated by Django 3.2.8 on 2021-11-05 23:36

import API.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to=API.models.upload_path)),
            ],
        ),
    ]
